name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java:
          - 11
          - 25
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: sbt/setup-sbt@v1
    - uses: coursier/cache-action@v8
    - shell: bash
      run: sbt -v
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ test"
    - uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
      if: always()
      with:
        report_paths: '**/target/test-reports/*.xml'
        require_tests: true
        check_name: "${{ matrix.java }}"
